# Generated by Django 4.0 on 2021-12-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tittle',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
