# Generated by Django 4.0 on 2021-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Web', '0002_film_year_alter_film_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='lenght',
            field=models.DateTimeField(max_length=5, null=True),
        ),
    ]
