# Generated by Django 4.0 on 2021-12-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Web', '0003_film_lenght'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
    ]
