# Generated by Django 4.0 on 2021-12-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Web', '0004_remove_film_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='lenght',
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='film',
            name='premiere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
    ]
