# Generated by Django 4.0 on 2021-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Web', '0005_remove_film_lenght_film_description_film_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
