# Generated by Django 4.0.2 on 2022-02-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_Web', '0008_alter_dodatkoweinfo_gatunek_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (0, 'Inne'), (2, 'Komedia'), (3, 'Sci-fi'), (4, 'Dramat')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(to='Film_Web.Film')),
            ],
        ),
    ]
